### ISSUE TITLE
Reference for Graph Pooling

### ISSUE THREAD

**Issue by wsjeon** [Thinklab-SJTU/PPO-BiHyb#1]
Hi. Thanks for the interesting results with codes. 

I'd like to know if there's any reference paper used for the graph pooling (https://github.com/Thinklab-SJTU/PPO-BiHyb/blob/38737030e2d51f5311b79b4e1453672ccb8be46a/pyg_graph_models.py#L89-L134). I read your paper to find the reference but couldn't figure out what it is. 

Thanks!

**Comment by rogerwwww** [comment]
Hi there, 

We follow the common practice of the attention mechanism to compute the weights in the many-to-one pooling operation. Perhaps you may cite the "Attention is all you need" for the reference ;)
