### ISSUE TITLE
dag_ppo_bihyb_train.py

### ISSUE THREAD

**Issue by chenyuezheng** [Thinklab-SJTU/PPO-BiHyb#3]
![image](https://user-images.githubusercontent.com/103935243/190356460-5c031c77-7da5-4e33-99cd-91c57ac7bfe2.png)

请问一下，这个问题怎么解决，感谢！

**Comment by rogerwwww** [comment]
1) 建议先不装tensorboard，训练测试部分能运行即可。tensorboard属于锦上添花

2) 如果需要tensorboard, here are the tensorflow/tensorboard versions in my environment:

```
tensorboard             1.14.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.0
tensorflow              1.14.0
tensorflow-estimator    1.14.0
```
