### ISSUE TITLE
关于代码的一些问题

### ISSUE THREAD

**Issue by ffaner1997** [Thinklab-SJTU/PPO-BiHyb#4]
![image](https://user-images.githubusercontent.com/49947822/190359584-72e86aae-135b-46e0-b9ec-53235f98bb5e.png)
您好！冒昧打扰您了！在学习您代码的过程中遇到了这样的问题，想问下您这个文件是什么文件？或者对于这个问题您有什么好的建议吗？

**Comment by rogerwwww** [comment]
Please specify the ``test_model_weight`` parameter.
