### ISSUE TITLE
dag_ppo_bihyb_train.py

### ISSUE THREAD

**Issue by chenyuezheng** [Thinklab-SJTU/PPO-BiHyb#6]
![image](https://user-images.githubusercontent.com/103935243/190582480-54b9af13-ba55-4da8-8509-6eb31f7dbd2f.png)

您好！冒昧打扰您了！在学习您代码的过程中遇到了这样的问题，请问一下这个问题该怎么解决？感谢！

**Comment by rogerwwww** [comment]
Same issue as https://github.com/Thinklab-SJTU/PPO-BiHyb/issues/5. 
Did you modify anything? The code works with no error on my side.
