### ISSUE TITLE
A Bi-Level Framework for Learning to Solve Combinatorial Optimization on Graphs

### ISSUE THREAD

**Issue by chenyuezheng** [Thinklab-SJTU/PPO-BiHyb#7]
你好，大佬，请问这篇论文的GED数据集需要在虚拟机环境下跑吗，我是在pycharm里面写的代码，运行代码显示找不到a_star，需要装Microsoft Visual C++Build Tools这个软件吗，感谢大佬！

**Comment by rogerwwww** [comment]
Hi there,

As noted in https://github.com/Thinklab-SJTU/PPO-BiHyb#environment-set-up, you need to compile the A-star module by: ``python3 setup.py build_ext --inplace``

**Comment by chenyuezheng** [comment]
![image](https://user-images.githubusercontent.com/103935243/195873130-33abf563-9756-4de4-b3bf-9c6660af1474.png)
感谢大佬，前一个问题已经解决，请问一下HCP实验中的数据集在windows10的anaconda prompt如何编译，我看这上面是在虚拟机里make的

**Comment by rogerwwww** [comment]
Sorry，Windows下应该怎么做我不太清楚。推荐你用WSL吧
