### ISSUE TITLE
你好，请问一下，1)代码里的first_wave,fresh_durations，rest_wave是什么含义，debug这里面的结构没太搞懂;  2)这个数据集的2g,5g,10g这些的具体含义是什么;如有打扰，实属抱歉，还望不吝赐教，十分感谢！

### ISSUE THREAD

**Issue by chenyuezheng** [Thinklab-SJTU/PPO-BiHyb#8]
![image](https://user-images.githubusercontent.com/103935243/202975461-a9bdf491-2ae5-46db-9600-3f59b81afd59.png)
![image](https://user-images.githubusercontent.com/103935243/202975888-ff7a5306-b82f-40b7-b279-5b9403e9f436.png)

**Comment by rogerwwww** [comment]
Thanks for your interest in our paper!

Our co-authors from Ant Group contributed this part of the code, and you may have to refer to them (the second and third authors of this paper) for details. In my understanding, first_wave, fresh_duration, and rest_wave are time consumption metrics for this task.
